#!/bin/sh

case "${DESKTOP_SESSION-}" in
	awesome|dwm)
		setxkbmap -layout us,ru -option grp:alt_shift_toggle,compose:ralt,grp_led:scroll
		/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
		compton -d
		aw-server &
		aw-watcher-window &
		aw-watcher-afk &
		xss-lock -- i3lock -c000000 &
		tilda &
		xxkb &
		nm-applet &
		;;
esac

exec $DESKTOP_SESSION
